version: "2"
## Configuration Documentation: https://golangci-lint.run/docs/configuration/file/
run:
  concurrency: 16
  timeout: 5m
  issues-exit-code: 1
  tests: true # report bugs in tests
  allow-parallel-runners: false
  go: "" # Keep this empty to use the Go version from the go.mod file

linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/docs/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: standard
  settings:
    cyclop:
      # The maximal code complexity to report - Default: 10
      max-complexity: 15
      # The maximal average package complexity - Default: 0.0
      # If it's higher than 0.0 (float) the check is enabled.
      package-average: 0.0
    funlen:
      lines: 100
    gocognit:
      min-complexity: 30
    lll:
      # Max line length, lines longer will be reported - Default: 120.
      line-length: 100
      # Tab width in spaces - Default: 1
      tab-width: 1
    nestif:
      min-complexity: 7
    gosec:
      excludes:
        - G108 # disable "Profiling endpoint is automatically exposed on /debug/pprof"
    staticcheck:
      checks:
        - "all"
        - "-ST1000" # disable package comment check
      initialisms:
        - id # allow 'id' instead of 'ID' in struct json tags
    varnamelen:
      max-distance: 6
      min-name-length: 2
      check-receiver: false
      check-return: false
      check-type-param: false
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names:
        - i # very very commonly short for index
  enable:
    - cyclop
    - forcetypeassert
    - funlen
    - gocognit
    - gocritic
    #- godot
    - gosec
    - lll
    - modernize
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - perfsprint
    - unparam
    - varnamelen
    - wrapcheck
    - wsl_v5
  disable:
    ### Deprecated linters
    - wsl # currently using wsl_v5

    ### Explicitly disabled linters
    - depguard # checks if packages are in an "allowed" list... not needed
    - noinlineerr # i use inline errors because i find it more readable; deal with it
    - mnd # magic number detection - i calculate percentages or define layout proportions
    - exhaustive # check exhaustiveness of switch statements
    - exhaustruct # check for missing struct fields
    - gochecknoglobals # very intentionally I use globals where it makes sense
    - gochecknoinits # what's the problem with init()?

    ### May enable later:
    - revive # disable function comments for now...
    - godox # disable scanning for TODO/FIXME/BUG etc
    - unused # check for unused functions, vars & var slices

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 100
      tab-len: 1
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true
